/**
 * Supplier create / edit — C owns this file.
 *
 * One component for both: the only differences are which schema runs, which
 * mutation fires and what the button says.
 *
 * RHF + the Zod resolver. Hand-rolled form state is banned in this repo
 * (docs/components.md § Forms).
 */

import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect } from 'react';
import { Controller, useForm } from 'react-hook-form';
import { useNavigate, useParams } from 'react-router-dom';

import {
  Button,
  FormField,
  FormSelect,
  PageHeader,
  toast,
} from '@/components/ui';

import {
  createSupplier,
  fetchSupplier,
  supplierKeys,
  updateSupplier,
} from '../api';
import {
  supplierCreateSchema,
  supplierDefaults,
  supplierUpdateSchema,
} from '../schema';

const STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
];

/** Empty text inputs become null, never "" (docs/entities.md). */
const nullIfEmpty = { setValueAs: (value) => (value === '' ? null : value) };

/** The fields this form owns. Anything else the server sends is not ours. */
function toFormValues(supplier) {
  return {
    name: supplier.name,
    tin: supplier.tin,
    email: supplier.email,
    phone: supplier.phone,
    contactPerson: supplier.contactPerson,
    address: {
      line1: supplier.address?.line1 ?? null,
      line2: supplier.address?.line2 ?? null,
      city: supplier.address?.city ?? null,
      region: supplier.address?.region ?? null,
      country: supplier.address?.country ?? null,
      postalCode: supplier.address?.postalCode ?? null,
    },
    paymentTermsDays: supplier.paymentTermsDays,
    currency: supplier.currency,
    status: supplier.status,
    notes: supplier.notes,
  };
}

export function SupplierFormPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const isEdit = Boolean(id);

  const { data: supplier, isLoading } = useQuery({
    queryKey: supplierKeys.detail(id),
    queryFn: () => fetchSupplier(id),
    enabled: isEdit,
  });

  const {
    control,
    register,
    handleSubmit,
    reset,
    setError,
    formState: { errors, isSubmitting },
  } = useForm({
    // PATCH validates partially, POST validates the whole shape.
    resolver: zodResolver(isEdit ? supplierUpdateSchema : supplierCreateSchema),
    defaultValues: supplierDefaults,
  });

  // Populate once the record arrives — the query resolves after mount.
  useEffect(() => {
    if (supplier) reset(toFormValues(supplier));
  }, [supplier, reset]);

  const mutation = useMutation({
    mutationFn: (values) =>
      isEdit ? updateSupplier(id, values) : createSupplier(values),
    onSuccess: (saved) => {
      queryClient.invalidateQueries({ queryKey: supplierKeys.lists() });
      if (isEdit) {
        queryClient.invalidateQueries({ queryKey: supplierKeys.detail(id) });
      }
      // Same verb as the button that caused it.
      toast.success(isEdit ? 'Supplier saved' : 'Supplier created');
      navigate(`/suppliers/${saved.id}`);
    },
    onError: (error) => {
      // 422 carries `fields`, which maps straight onto the inputs.
      if (error.fields) {
        Object.entries(error.fields).forEach(([field, message]) =>
          setError(field, { message }),
        );
        toast.error('Could not save supplier', {
          description: 'Check the highlighted fields.',
        });
        return;
      }
      toast.error('Could not save supplier', { description: error.message });
    },
  });

  if (isEdit && isLoading) {
    return (
      <div className="mx-auto flex max-w-3xl flex-col gap-4 p-6">
        <div className="h-8 w-64 animate-pulse rounded-md bg-surface" />
        <div className="h-96 animate-pulse rounded-md border border-border bg-surface" />
      </div>
    );
  }

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-4 p-6">
      <PageHeader
        title={isEdit ? 'Edit supplier' : 'New supplier'}
        description={
          isEdit
            ? supplier?.code
            : 'The code is generated by the server once you save.'
        }
      />

      <form
        onSubmit={handleSubmit((values) => mutation.mutate(values))}
        className="flex flex-col gap-6"
      >
        <Section title="Identity">
          <FormField
            label="Name"
            required
            error={errors.name?.message}
            placeholder="Abay Industrial Supply"
            {...register('name')}
          />
          <FormField
            label="TIN"
            error={errors.tin?.message}
            hint="Tax identification number. Optional."
            {...register('tin', nullIfEmpty)}
          />
          <Controller
            name="status"
            control={control}
            render={({ field }) => (
              <FormSelect
                label="Status"
                name={field.name}
                value={field.value ?? ''}
                onChange={field.onChange}
                options={STATUS_OPTIONS}
                error={errors.status?.message}
                required
              />
            )}
          />
        </Section>

        <Section title="Contact">
          <FormField
            label="Contact person"
            error={errors.contactPerson?.message}
            {...register('contactPerson', nullIfEmpty)}
          />
          <FormField
            label="Email"
            type="email"
            error={errors.email?.message}
            placeholder="name@example-erp.test"
            {...register('email', nullIfEmpty)}
          />
          <FormField
            label="Phone"
            type="tel"
            error={errors.phone?.message}
            placeholder="+251-911-000-000"
            {...register('phone', nullIfEmpty)}
          />
        </Section>

        <Section title="Address">
          <FormField
            label="Street"
            error={errors.address?.line1?.message}
            {...register('address.line1', nullIfEmpty)}
          />
          <FormField
            label="Line 2"
            error={errors.address?.line2?.message}
            {...register('address.line2', nullIfEmpty)}
          />
          <FormField
            label="City"
            error={errors.address?.city?.message}
            {...register('address.city', nullIfEmpty)}
          />
          <FormField
            label="Region"
            error={errors.address?.region?.message}
            {...register('address.region', nullIfEmpty)}
          />
          <FormField
            label="Country"
            error={errors.address?.country?.message}
            hint="Two-letter code, e.g. ET."
            {...register('address.country', nullIfEmpty)}
          />
          <FormField
            label="Postal code"
            error={errors.address?.postalCode?.message}
            {...register('address.postalCode', nullIfEmpty)}
          />
        </Section>

        <Section title="Terms">
          <FormField
            label="Payment terms"
            type="number"
            min="0"
            max="365"
            required
            error={errors.paymentTermsDays?.message}
            hint="Days. How long we have to pay them."
            {...register('paymentTermsDays', { valueAsNumber: true })}
          />
          <FormField
            label="Currency"
            required
            error={errors.currency?.message}
            hint="Three-letter code, e.g. ETB."
            {...register('currency')}
          />
          <FormField
            label="Notes"
            type="textarea"
            rows={3}
            error={errors.notes?.message}
            {...register('notes', nullIfEmpty)}
          />
          {!isEdit && (
            <p className="text-xs text-text-muted">
              The balance starts at zero. It is calculated by the server from
              received purchase orders and payments, never entered by hand.
            </p>
          )}
        </Section>

        <div className="flex items-center gap-2">
          <Button type="submit" loading={isSubmitting || mutation.isPending}>
            {isEdit ? 'Save supplier' : 'Create supplier'}
          </Button>
          <Button
            type="button"
            variant="secondary"
            onClick={() => navigate(isEdit ? `/suppliers/${id}` : '/suppliers')}
          >
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}

/**
 * Local stand-in for the kit's specified `FormSection`, which is not built yet
 * (components/ui/index.js § Still to come). Swap when A ships it.
 */
function Section({ title, children }) {
  return (
    <fieldset className="flex flex-col gap-3 rounded-md border border-border bg-surface p-4">
      <legend className="px-1 text-sm font-semibold text-text">{title}</legend>
      {children}
    </fieldset>
  );
}
