/**
 * MSW worker setup — owned by A.
 *
 * Started from main.jsx only when VITE_USE_MOCKS=true. The worker script lives
 * at public/mockServiceWorker.js and is generated by `npx msw init public/`.
 */

// TODO(A): implement.
// import { setupWorker } from 'msw/browser';
// import { handlers } from './handlers';
// export const worker = setupWorker(...handlers);

export {};
