/**
 * MSW worker setup — owned by A.
 *
 * Started from main.jsx only when VITE_USE_MOCKS=true. The worker script at
 * public/mockServiceWorker.js is generated by `npx msw init public/` and is
 * committed; regenerate it after an msw major upgrade.
 */

import { setupWorker } from 'msw/browser';

import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
