/**
 * Product create / edit — C owns this file.
 *
 * One component for both, because the only differences are which schema runs,
 * which mutation fires and what the button says. Two files would drift.
 *
 * There is deliberately no quantity field. Stock changes only through an
 * adjustment record (docs/entities.md § Product) — the detail page owns that.
 *
 * RHF + the Zod resolver. Hand-rolled form state is banned in this repo
 * (docs/components.md § Forms).
 */

import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect } from 'react';
import { Controller, useForm } from 'react-hook-form';
import { useNavigate, useParams } from 'react-router-dom';

import { Button, FormField, FormSelect, PageHeader, toast } from '@/components/ui';

import { ProductMoneyField } from '../components/ProductMoneyField';
import {
  createProduct,
  fetchProduct,
  fetchProductCategories,
  productKeys,
  updateProduct,
} from '../api';
import {
  productCreateSchema,
  productDefaults,
  productUpdateSchema,
} from '../schema';

const UNIT_OPTIONS = [
  { value: 'pcs', label: 'Pieces' },
  { value: 'kg', label: 'Kilograms' },
  { value: 'ltr', label: 'Litres' },
  { value: 'box', label: 'Boxes' },
];

const STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'discontinued', label: 'Discontinued' },
];

/** The fields this form owns. Anything else the server sends is not ours. */
function toFormValues(product) {
  return {
    name: product.name,
    description: product.description,
    categoryId: product.categoryId,
    unitOfMeasure: product.unitOfMeasure,
    costPrice: product.costPrice,
    sellingPrice: product.sellingPrice,
    currency: product.currency,
    reorderLevel: product.reorderLevel,
    barcode: product.barcode,
    imageUrl: product.imageUrl,
    status: product.status,
  };
}

export function ProductFormPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const isEdit = Boolean(id);

  const { data: product, isLoading } = useQuery({
    queryKey: productKeys.detail(id),
    queryFn: () => fetchProduct(id),
    enabled: isEdit,
  });

  const { data: categories = [], isLoading: categoriesLoading } = useQuery({
    queryKey: productKeys.categories(),
    queryFn: fetchProductCategories,
    staleTime: 5 * 60 * 1000,
  });

  const {
    control,
    register,
    handleSubmit,
    reset,
    setError,
    watch,
    formState: { errors, isSubmitting },
  } = useForm({
    // PATCH validates partially, POST validates the whole shape.
    resolver: zodResolver(isEdit ? productUpdateSchema : productCreateSchema),
    defaultValues: productDefaults,
  });

  // Populate once the record arrives. `reset` rather than defaultValues,
  // because the query resolves after the form has already mounted.
  useEffect(() => {
    if (product) reset(toFormValues(product));
  }, [product, reset]);

  const currency = watch('currency') || 'ETB';

  const mutation = useMutation({
    mutationFn: (values) =>
      isEdit ? updateProduct(id, values) : createProduct(values),
    onSuccess: (saved) => {
      queryClient.invalidateQueries({ queryKey: productKeys.lists() });
      if (isEdit) {
        queryClient.invalidateQueries({ queryKey: productKeys.detail(id) });
      }
      // Same verb as the button that caused it.
      toast.success(isEdit ? 'Product saved' : 'Product created');
      navigate(`/products/${saved.id}`);
    },
    onError: (error) => {
      // 422 carries `fields`, which maps straight onto the inputs with no
      // extra work — docs/api-contract.md §1.
      if (error.fields) {
        Object.entries(error.fields).forEach(([field, message]) =>
          setError(field, { message }),
        );
        toast.error('Could not save product', {
          description: 'Check the highlighted fields.',
        });
        return;
      }
      toast.error('Could not save product', { description: error.message });
    },
  });

  if (isEdit && isLoading) {
    return (
      <div className="mx-auto flex max-w-3xl flex-col gap-4 p-6">
        <div className="h-8 w-64 animate-pulse rounded-md bg-surface" />
        <div className="h-96 animate-pulse rounded-md border border-border bg-surface" />
      </div>
    );
  }

  const categoryOptions = categories.map((category) => ({
    value: category.id,
    label: category.name,
  }));

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-4 p-6">
      <PageHeader
        title={isEdit ? 'Edit product' : 'New product'}
        description={
          isEdit
            ? product?.sku
            : 'The SKU is generated by the server once you save.'
        }
      />

      <form
        onSubmit={handleSubmit((values) => mutation.mutate(values))}
        className="flex flex-col gap-6"
      >
        <Section title="Identity">
          <FormField
            label="Name"
            required
            error={errors.name?.message}
            placeholder="Galvanised Steel Sheet 2mm"
            {...register('name')}
          />

          <Controller
            name="categoryId"
            control={control}
            render={({ field }) => (
              <FormSelect
                label="Category"
                name={field.name}
                value={field.value ?? ''}
                onChange={field.onChange}
                options={categoryOptions}
                loading={categoriesLoading}
                error={errors.categoryId?.message}
                required
                searchable
              />
            )}
          />

          <FormField
            label="Description"
            type="textarea"
            rows={3}
            error={errors.description?.message}
            {...register('description', {
              // Missing values are null, never "" (docs/entities.md).
              setValueAs: (value) => (value === '' ? null : value),
            })}
          />

          <FormField
            label="Barcode"
            error={errors.barcode?.message}
            hint="Optional."
            {...register('barcode', {
              setValueAs: (value) => (value === '' ? null : value),
            })}
          />
        </Section>

        <Section title="Pricing">
          {/* Money in and out as integer minor units — never a float, and never
              a plain number input (docs/components.md § Forms). */}
          <Controller
            name="costPrice"
            control={control}
            render={({ field }) => (
              <ProductMoneyField
                label="Cost price"
                name={field.name}
                value={field.value}
                currency={currency}
                onChange={field.onChange}
                error={errors.costPrice?.message}
                required
                hint="What you pay your supplier."
              />
            )}
          />

          <Controller
            name="sellingPrice"
            control={control}
            render={({ field }) => (
              <ProductMoneyField
                label="Selling price"
                name={field.name}
                value={field.value}
                currency={currency}
                onChange={field.onChange}
                error={errors.sellingPrice?.message}
                required
                hint="What your customer pays."
              />
            )}
          />

          <FormField
            label="Currency"
            required
            error={errors.currency?.message}
            hint="Three-letter code, e.g. ETB."
            {...register('currency')}
          />
        </Section>

        <Section title="Stock settings">
          <Controller
            name="unitOfMeasure"
            control={control}
            render={({ field }) => (
              <FormSelect
                label="Unit of measure"
                name={field.name}
                value={field.value ?? ''}
                onChange={field.onChange}
                options={UNIT_OPTIONS}
                error={errors.unitOfMeasure?.message}
                required
              />
            )}
          />

          <FormField
            label="Reorder level"
            type="number"
            step="any"
            min="0"
            required
            error={errors.reorderLevel?.message}
            hint="Below this, the product shows a low-stock badge."
            {...register('reorderLevel', { valueAsNumber: true })}
          />

          <Controller
            name="status"
            control={control}
            render={({ field }) => (
              <FormSelect
                label="Status"
                name={field.name}
                value={field.value ?? ''}
                onChange={field.onChange}
                options={STATUS_OPTIONS}
                error={errors.status?.message}
                required
              />
            )}
          />

          {!isEdit && (
            <p className="text-xs text-text-muted">
              Stock starts at zero. It changes only through a stock adjustment,
              so there is always an audit trail — use “Adjust stock” on the
              product once it exists.
            </p>
          )}
        </Section>

        <div className="flex items-center gap-2">
          <Button type="submit" loading={isSubmitting || mutation.isPending}>
            {isEdit ? 'Save product' : 'Create product'}
          </Button>
          <Button
            type="button"
            variant="secondary"
            onClick={() => navigate(isEdit ? `/products/${id}` : '/products')}
          >
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}

/**
 * Local stand-in for the kit's specified `FormSection`, which is not built yet
 * (components/ui/index.js § Still to come). Swap when A ships it.
 */
function Section({ title, children }) {
  return (
    <fieldset className="flex flex-col gap-3 rounded-md border border-border bg-surface p-4">
      <legend className="px-1 text-sm font-semibold text-text">{title}</legend>
      {children}
    </fieldset>
  );
}
